# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "@renerocksai"
email:
description: >- # this means to ignore newlines until "baseurl:"
  Rene Schallner's personal web page and blog. Computer Science, Data Science, Artificial Intelligence, Deep Learning
twitter_username: renerocksai
github_username: renerocksai
minimal_mistakes_skin: "air"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 4 # amount of posts to show
paginate_path: /blog/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

kramdown:
  auto_ids: true

include:
  - _pages
  - _projects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Rene Schallner"
  avatar : "/assets/images/reneglasses.png"
  bio    : "Software engineer turned researcher, AI heavy data scientist with strong computer science and electronics skills"
  links:
      #    - label: "Website"
      #icon: "fas fa-fw fa-link"
      #url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/renerocksai"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/renerocksai"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rene-schallner-901701144/"
    - label: "Sponsor"
      icon: "fab fa fa-heart"
      url: "https://github.com/sponsors/renerocksai"
      style: "color:#cd0f2d"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/renerocksai"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/renerocksai"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/rene-schallner-901701144/"
    - label: "Sponsor"
      icon: "fa fa-heart"
      url: "https://github.com/sponsors/renerocksai"
      style: "color:#cd0f2d"


collections:
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-QRBME2DJ7C"
    anonymize_ip: false # default
